### ISSUE TITLE
Incomplete installation leads to ModuleNotFoundError

### ISSUE THREAD

**Issue by mbendjilali** [romainloiseau/LearnableEarthParser#1]
Hello,
Congratulations on your article, and thank you for sharing your code! I've tried to run it, but I keep running into errors, first caused by the _sampler.pyx module, which was not yet compiled. So I wrote a short `setup.py` to compile it :
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize
import numpy
import os

setup_dir = os.path.dirname(os.path.abspath(__file__))

extensions = [
    Extension(
        "*",
        [setup_dir + "/learnableearthparser/fast_sampler/_sampler.pyx"],
        include_dirs=[numpy.get_include()],
    )
]

setup(ext_modules=cythonize(extensions))
```
The inclusion of numpy was made necessary by some `fatal error: numpy/arrayobject.h: No such file or directory`. I tried to run the main script back, but I am now stuck in a dead end because of this error : 
```
ImportError: /LearnableEarthParser/learnableearthparser/fast_sampler/_sampler.cpython-39-x86_64-linux-gnu.so: undefined symbol: sample_on_batch
```

Could you give me a hand ? :hand:

**Comment by romainloiseau** [comment]
Hello,

Thank you for your message. I didn't have any problems running this part of the code, and I know some colleagues used it without any problems too. As said in the readme, I took this code from the following repository : [https://github.com/paschalidoud/superquadric_parsing](https://github.com/paschalidoud/superquadric_parsing)

Maybe you will find answers here? Tell me if you still cannot use the repo so that I look for the issue.

Best,

Romain

**Comment by mbendjilali** [comment]
Yes, I tried to install superquadric_parsing, but its requirements are deprecated as torch 0.4.1 is not made available anymore on the PyTorch public channel, and the repository hasn't been maintained that well. There are some wheels downloadable from [the pytorch website](https://download.pytorch.org/whl/cu100/torch_stable.html) that require CUDA <= 9.0 though.

For now, I can install the superquadric_parsing module in its own environment, set with Python 3.7.
I first run `pip install https://download.pytorch.org/whl/cu90/torch-0.4.1-cp37-cp37m-linux_x86_64.whl`,
then `pip install -r requirements.txt`,
and finally `pip install -e .`.

However, this conflicts with the `environment.yml` file from LearnableEarthParser... :cry:

**Comment by mbendjilali** [comment]
Oof, I think I'm misunderstanding the README. I was trying to install the whole superquadric_parsing module, which gets me really confused at how you manage to run two incompatibles modules, but I just have to install the `learnableearthparser/fast_sampler` subfolder ?

**Comment by mbendjilali** [comment]
I suggest you modify the readme instructions about the fast_sampler module. Here is the `setup.py` file that should be added to the root of the repository to install the fast_sampler module.
```
from setuptools import find_packages, setup, Extension
from Cython.Build import cythonize
import numpy

def get_extensions():
    return cythonize([
        Extension(
            "learnableearthparser.fast_sampler._sampler",
            [
                "learnableearthparser/fast_sampler/_sampler.pyx",
                "learnableearthparser/fast_sampler/sampling.cpp"
            ],
            language="c++11",
            libraries=["stdc++"],
            include_dirs=[numpy.get_include()],
            extra_compile_args=["-std=c++11", "-O3"]
        )
    ])

setup(
    name="learnableearthparser",
    ext_modules=get_extensions(),
    packages=find_packages(exclude=["docs", "tests"]),
    include_dirs=[numpy.get_include()],
    install_requires=[],
)
```
The bash command is then : `python setup.py build_ext --inplace`

**Comment by xbais** [comment]
For anybody still stuck here...and wanting a quick solution, the following might just work out for you... :wink: 
1. Just install the [Superquadratic Parsing Git repo](https://github.com/paschalidoud/superquadric_parsing). (you can probably try using PyTorch=1.11.0 instead of the old PyTorch=0.4.1 that is required for this repo without any issues)
2. Install this repo using the installation steps in the [README](https://github.com/romainloiseau/LearnableEarthParser/blob/main/README.md).
3. **The Important Step** : In your copy of the code for this repo, just replace the content of file [learnableearthparser/fast_sampler/__init__.py](https://github.com/romainloiseau/LearnableEarthParser/blob/main/learnableearthparser/fast_sampler/__init__.py) with the following content:

```python
from learnable_primitives.fast_sampler._sampler import step_eta, step_omega, collect_etas, collect_omegas, fast_sample, fast_sample_on_batch
```
(This will by-pass this redundant `fast_sampler` module present here which is causing the error. It will instead use the one that has already been installed from the other repo.)

Best,
Aakash Singh Bais

**Comment by romainloiseau** [comment]
Thanks a lot for solving the issue, I will update the repo soon!
